name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

env:
        APP_NAME: ${{ github.repository }}
        BRANCH: ${{ github.ref }}

jobs:
  check_licenses:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v2

    - name: Install jq env
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Download script
      run: |
        wget -q -O check_licenses.sh https://raw.githubusercontent.com/th2-net/.github/th2-1836-json-files-update/license-compliance/check_licenses.sh
        chmod +x ./check_licenses.sh
    
    - name: Run check_licenses script
      run: ./check_licenses.sh java
      shell: bash
    
    - name: Check exit status and set workflow status
      run: |
        if [ $? -eq 0 ]; then
          echo "All certificates are valid"
          echo "Success"
        else
          echo "Workflow failed due to faulty certificates"
          echo "Failure"
          exit 1
        fi
      id: set_status

    - name: Set workflow status
      run: |
        if [[ "${{ steps.set_status.outputs.value }}" == "Success" ]]; then
          echo "Success"
        else
          echo "Failure"
        fi
      id: final_status

    - name: Get version
      run:
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')              

    - name: Uploading results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: licenses_check-$APP_NAME-$VERSION
        path: ./licenses_check/

      #  build-job:
      #    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
      #    with:
      #      build-target: 'Docker'
      #      docker-username: ${{ github.actor }}
      #    secrets:
      #      docker-password: ${{ secrets.GITHUB_TOKEN }}
