name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  check_licenses:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v2
      # with:
      #   repository: th2-net/.github
      #   ref: th2-1836-json-files-update
    - name: Download and Extract script folder
      run: |
        wget https://github.com/th2-net/.github/archive/refs/heads/th2-1836-json-files-update/license-compliance.zip
        unzip license-compliance.zip
        chmod +x ./license-compliance/check_licenses.sh
    - name: Run check_licenses script
      run: ./license-compliance/check_licenses.sh java
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}