name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  check_licenses:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v2

    - name: Install jq env
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Download script
      run: |
        wget -q -O check_licenses.sh https://raw.githubusercontent.com/th2-net/.github/th2-1836-json-files-update/license-compliance/check_licenses.sh
        #unzip license-compliance.zip
        chmod +x ./check_licenses.sh
    
    - name: Run check_licenses script
      run: ./check_licenses.sh java
      shell: bash

    # - name: Uploading results
    #   run: |
    #     zip -r licenses_check.zip licenses_check
    - name: Uploading results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: licenses_check-$(format('%Y-%m-%d_%H-%M-%S', github.run_started))
        path: "licenses_check/*.csv"

      #  build-job:
      #    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
      #    with:
      #      build-target: 'Docker'
      #      docker-username: ${{ github.actor }}
      #    secrets:
      #      docker-password: ${{ secrets.GITHUB_TOKEN }}
