name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md

jobs:
  check_licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Run check_licenses script
      run: |
        chmod +r ./license-compliance/check_licenses.sh
        ./license-compliance/check_licenses.sh java

    # runs-on: ubuntu-latest
    # steps:
    # - name: checkout actions
    #   uses: actions/checkout@v2
    #   with:
    #     repository: th2-net/.github
    #     ref: th2-1836-json-files-update
    # - name: Run check_licenses script
    #   run: ./license-compliance/check_licenses.sh java
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}